### PR TITLE
Feature/4.2.0 rc.1

### PR DESCRIPTION
**Pull request by andreea-pasare**
- eInvoicing module development
- fixing github issues from 4.2.0 milestone
- no manual modifications on OWL/SHACL output were done

### CODE REVIEW

**Comment by cristianvasquez** [comment]
- https://github.com/OP-TED/ePO/issues/554 still is xsd:Integer

I can see the following are addressed: 

- https://github.com/OP-TED/ePO/issues/593
- https://github.com/OP-TED/ePO/issues/617
- https://github.com/OP-TED/ePO/issues/652
- https://github.com/OP-TED/ePO/issues/653
- https://github.com/OP-TED/ePO/issues/634
- https://github.com/OP-TED/ePO/issues/644
- https://github.com/OP-TED/ePO/issues/633
- https://github.com/OP-TED/ePO/issues/629
- https://github.com/OP-TED/ePO/issues/657
- https://github.com/OP-TED/ePO/issues/634
- https://github.com/OP-TED/ePO/issues/617


https://github.com/OP-TED/ePO/issues/624 `isSubcontractingPercentageKnown` ~could have a naming/range issue~ should have boolean as range

Inspecting random properties I saw that `hasAccountingCost` range is rdf:PlainLiteral [0..1]. Is this correct? I thought it could be a epo:MonetaryValue [0..1].

**Comment by AchillesDougalis** [comment]
Hi, `https://github.com/OP-TED/ePO/issues/554 still is xsd:Integer` yes, we will deal with this in ePO 5.0.0 as it is mentioned in the comments.

**Comment by cristianvasquez** [comment]
Hi @AchillesDougalis, I've checked the issues from the milestone, https://github.com/OP-TED/ePO/milestone/10 are there others to add to the pull request?

**Comment by AchillesDougalis** [comment]
> Hi @AchillesDougalis, I've checked the issues from the milestone, https://github.com/OP-TED/ePO/milestone/10 are there others to add to the pull request?

No, these are all for now.

**Comment by cristianvasquez** [comment]
Then the only issue I found is that isSubcontractingPercentageKnown should have boolean as range https://github.com/OP-TED/ePO/issues/624

**Pull request merged**
